Create variable to avoid reference error.
The error caused is this:
I've been getting this error in production (node 5.11.1) whenever the server is started. This change fixes that.

```
ReferenceError: duration is not defined
    at cache ([...]/node_modules/apicache/lib/apicache.js:111:14)
```